services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 9000:8080
    networks:
      - websearch-network
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      - SEARXNG_URL=http://searxng:8080
    ports:
      - "6743:6743"
    networks:
      - websearch-network
    depends_on:
      - searxng
    restart: unless-stopped

  frontend:
    build: ./searxngx
    ports:
      - "3000:80"
    networks:
      - websearch-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  websearch-network:
    driver: bridge

volumes:
  backend-dbstore:
  uploads:
